#!/bin/sh

# nrd-list-downloader for PFSense
# https://github.com/Lightbox32/PFSense-nrd-list-downloader
# Copyright (C) 2022 ~ Fernando J. Kohan
# Based on work by Peter Dave Hello
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

DIR="/var/db/pfblockerng/nrd"
DAY_RANGE="${DAY_RANGE:-14}"
DAILY_DIR="${DAILY_DIR:-daily-free}"
TEMP_FILE="$(mktemp)"
TARGET_FILE="nrd-${DAY_RANGE}days-free.txt"

BASE_URL="https://whoisds.com/whois-database/newly-registered-domains"
COMMENT="# NRD list generated by nrd-list-downloader, on $(date '+%Y-%m-%d'), data source: WhoisDS.com"

cd "$DIR"

mkdir -p "$DAILY_DIR"

echo "You are using nrd-list-downloader to download NRD(Newly Registered Domain) list ..."

echo "NRD list of the last $DAY_RANGE will be downloaded."

echo "$COMMENT" >> "$TEMP_FILE"

find "$DAILY_DIR" -mtime +"$DAY_RANGE" -type f -delete

i="$DAY_RANGE"

while [ "$i" -gt "0" ]; do
    DATE="$(date -v -${i}d '+%Y-%m-%d')"
    FILE="${DAILY_DIR}/${DATE}"

    if [ -s "$FILE" ] && [ "$(grep -vc '^$' "$FILE")" -ge "1" ] ; then
        echo "$FILE existed with $(grep -vc '^$' "$FILE") domains, skip the download and decompress process ..."
    else
        printf "%s" "Download and decompress $DATE data ... "

	  URL=$(perl -MMIME::Base64 -e "print encode_base64 ('${DATE}.zip');")

	  curl -sSLo- "${BASE_URL}/${URL}/nrd" | bsdtar -xO | tr -d '\015' >> "$FILE"
        echo "" >> "$FILE"
        echo "$(grep -vc '^$' "$FILE") domains found."
    fi
    echo "# ${DATE} NRD start" >> "$TEMP_FILE"
    cat "$FILE" >> "$TEMP_FILE"
    echo "# ${DATE} NRD end" >> "$TEMP_FILE"
    i="$((i - 1))"
done

echo "$COMMENT" >> "$TEMP_FILE"

chmod +r "$TEMP_FILE"
mv "$TEMP_FILE" "$TARGET_FILE"

echo "NRD list for the last $DAY_RANGE days saved to $TARGET_FILE, $(grep -cvE '^(#|$)' "$TARGET_FILE") domains found."
